
environments:
  development:


      dataSource:
            pooled : false
            jmxExport : true
            driverClassName: com.mysql.jdbc.Driver
            username: root
            password: root
            dbCreate: update
            url: jdbc:mysql://localhost:3306/linksharing
#            logSql : true
            formatSql: true
            dialect : org.hibernate.dialect.MySQL5InnoDBDialect
